######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 13 01:25:09 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += a.h ida.h mainwindow.h
FORMS += mainwindow.ui
SOURCES += a.cpp ida.cpp main.cpp mainwindow.cpp

RESOURCES += \
    resources.qrc

